[package]
name = "finchers-test"
version = "0.11.0-pre"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
finchers-core = { version = "0.11.0-pre", path = "../finchers-core" }
futures = "0.1.21"
http = "0.1.5"
