tag-prefix = "v"
disable-push = true
no-dev-version = true
pre-release-commit-message = "(cargo-release) bump version to {{version}}"
tag-message = "(cargo-release) version {{version}}"

pre-release-hook = ["cargo", "publish", "--dry-run"]

[[pre-release-replacements]]
file = "README.md"
search = "https://deps.rs/crate/finchers-juniper/[a-z0-9\\.-]+"
replace = "https://deps.rs/crate/finchers-juniper/{{version}}"

[[pre-release-replacements]]
file = "README.md"
search = "finchers-juniper = \"[a-z0-9\\.-]+\""
replace = "finchers-juniper = \"{{version}}\""

[[pre-release-replacements]]
file = "src/lib.rs"
search = "https://docs.rs/finchers-juniper/[a-z0-9\\.-]+"
replace = "https://docs.rs/finchers-juniper/{{version}}"
