dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/

script:
  - cargo update
  - cargo build --all-features

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - rust: 1.29.1
    - rust: beta

    - rust: stable
      before_script:
        - rustup component add rustfmt-preview clippy-preview
      script: >-
        cargo fmt -- --check &&
        cargo update &&
        rake ci_flow &&
        if [[ "${TRAVIS_PULL_REQUEST_BRANCH:-}" = release-* ]]; then; cargo publish --dry-run; fi

    - rust: nightly
      sudo: required
      addons:
        apt:
          packages:
            - libssl-dev
      before_script: |
        cargo +nightly tarpaulin --version || {
          RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin
        }
      after_success: |
        set -e
        cargo +nightly tarpaulin --out Xml --all-features
        bash <(curl -s https://codecov.io/bash)

    - rust: stable
      env: DEPLOY_API_DOC
      before_script:
      script: |
        set -e
        rm -rf target/doc
        cargo update
        cargo doc --no-deps --all-features -p askama -p tera -p handlebars -p horrorshow
        cargo doc --no-deps --all-features
        rm -f target/doc/.lock
        echo '<meta http-equiv="refresh" content="0;URL=finchers_template/index.html">' > target/doc/index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: finchers-rs/finchers-template
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
