version: 2
jobs:
  build:
    docker:
      - image: xd009642/tarpaulin
    steps:
      - checkout
      - run:
          name: Run tarpaulin
          command: >-
            cargo tarpaulin --out Xml &&
            bash <(curl -s https://codecov.io/bash)
