cargo-features = ["edition"]

[package]
name = "example-template-tera"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "template-tera"
path = "src/main.rs"
doc = false

[dependencies]
finchers = { path = "../.." }
tera = "0.11.12"
failure = "0.1.2"
http = "0.1.10"
