#!/bin/bash

set -e

BRANCH="$(git symbolic-ref --short HEAD)"
[[ "${BRANCH:-}" = wip-* ]] && exit 0

(set -x; cargo test)

if [[ "${BRANCH:-}" = release-* ]]; then
    (set -x; cargo publish --dry-run)
fi

if which cargo-fmt >/dev/null 2>&1; then
    (set -x; cargo fmt -- --check)
fi

if which cargo-clippy >/dev/null 2>&1; then
    (set -x; cargo clippy --tests)
fi
