[package]
name = "test_edition_2018"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[dependencies]
finchers = { version = "0.12.0-alpha.8", path = "../.." }
