[package]
name = "test-edition2018"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[lib]
name = "test_edition2018"
path = "lib.rs"

[dependencies]
finchers = { path = "../.." }
