[package]
name = "doctest"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.doubter]
version = "0.1"
default-features = false

[dev-dependencies]
finchers = { path = ".." }
izanami = "0.1.0-preview.1"
