[package]
name = "example-websocket"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[[bin]]
name = "example_websocket"
path = "src/main.rs"
doc = false

[dependencies]
finchers = "0.13"
finchers-tungstenite = "0.2"

futures = "0.1.24"
http = "0.1.13"
pretty_env_logger = "0.2.4"
log = "0.4.5"
tungstenite = "0.6.0"
