//! CORS support in Finchers.

#![doc(html_root_url = "https://docs.rs/finchers-cors/0.1.0-dev")]
#![deny(
    missing_docs,
    missing_debug_implementations,
    nonstandard_style,
    rust_2018_compatibility,
    rust_2018_idioms,
    unused
)]
#![forbid(clippy::unimplemented)]
#![doc(test(attr(deny(warnings))))]

use {
    either::Either,
    failure::Fail,
    finchers::{
        action::{ActionContext, EndpointAction, Preflight, PreflightContext},
        endpoint::{Endpoint, IsEndpoint},
        error::{Error, HttpError},
        output::IntoResponse,
    },
    futures::Poll,
    http::{
        header::{self, HeaderName, HeaderValue},
        Method, Request, Response, StatusCode, Uri,
    },
    std::{collections::HashSet, sync::Arc, time::Duration},
};

/// A `Wrapper` for building an endpoint with CORS.
#[derive(Debug, Default)]
pub struct CorsFilter {
    origins: Option<HashSet<Uri>>,
    methods: Option<HashSet<Method>>,
    headers: Option<HashSet<HeaderName>>,
    max_age: Option<Duration>,
    allow_credentials: bool,
}

impl CorsFilter {
    /// Creates a `CorsFilter` with the default configuration.
    pub fn new() -> CorsFilter {
        Default::default()
    }

    #[allow(missing_docs)]
    pub fn allow_origin(mut self, origin: impl Into<Uri>) -> CorsFilter {
        self.origins
            .get_or_insert_with(Default::default)
            .insert(origin.into());
        self
    }

    #[allow(missing_docs)]
    pub fn allow_origins(mut self, origins: impl IntoIterator<Item = Uri>) -> CorsFilter {
        self.origins
            .get_or_insert_with(Default::default)
            .extend(origins);
        self
    }

    #[allow(missing_docs)]
    pub fn allow_method(mut self, method: Method) -> CorsFilter {
        self.methods
            .get_or_insert_with(Default::default)
            .insert(method);
        self
    }

    #[allow(missing_docs)]
    pub fn allow_methods(mut self, methods: impl IntoIterator<Item = Method>) -> CorsFilter {
        self.methods
            .get_or_insert_with(Default::default)
            .extend(methods);
        self
    }

    #[allow(missing_docs)]
    pub fn allow_header(mut self, header: HeaderName) -> CorsFilter {
        self.headers
            .get_or_insert_with(Default::default)
            .insert(header);
        self
    }

    #[allow(missing_docs)]
    pub fn allow_headers(mut self, headers: impl IntoIterator<Item = HeaderName>) -> CorsFilter {
        self.headers
            .get_or_insert_with(Default::default)
            .extend(headers);
        self
    }

    #[allow(missing_docs)]
    pub fn allow_credentials(self, enabled: bool) -> CorsFilter {
        CorsFilter {
            allow_credentials: enabled,
            ..self
        }
    }

    #[allow(missing_docs)]
    pub fn max_age(self, max_age: Duration) -> CorsFilter {
        CorsFilter {
            max_age: Some(max_age),
            ..self
        }
    }

    #[allow(missing_docs)]
    pub fn apply<E>(self, endpoint: E) -> CorsEndpoint<E>
    where
        E: IsEndpoint,
    {
        let methods = self.methods.unwrap_or_else(|| {
            vec![
                Method::GET,
                Method::POST,
                Method::PUT,
                Method::HEAD,
                Method::DELETE,
                Method::PATCH,
                Method::OPTIONS,
            ]
            .into_iter()
            .collect()
        });

        let methods_value = HeaderValue::from_shared(
            methods
                .iter()
                .enumerate()
                .fold(String::new(), |mut acc, (i, m)| {
                    if i > 0 {
                        acc += ",";
                    }
                    acc += m.as_str();
                    acc
                })
                .into(),
        )
        .expect("should be a valid header value");

        let headers_value = self.headers.as_ref().map(|hdrs| {
            HeaderValue::from_shared(
                hdrs.iter()
                    .enumerate()
                    .fold(String::new(), |mut acc, (i, hdr)| {
                        if i > 0 {
                            acc += ",";
                        }
                        acc += hdr.as_str();
                        acc
                    })
                    .into(),
            )
            .expect("should be a valid header value")
        });

        CorsEndpoint {
            endpoint,
            inner: Arc::new(Inner {
                origins: self.origins,
                methods,
                methods_value,
                headers: self.headers,
                headers_value,
                max_age: self.max_age,
                allow_credentials: self.allow_credentials,
            }),
        }
    }
}

/// An endpoint which represents a route with CORS handling.
///
/// The value of this type is generated by `CorsFilter::wrap()`.
#[derive(Debug)]
pub struct CorsEndpoint<E> {
    endpoint: E,
    inner: Arc<Inner>,
}

#[derive(Debug)]
struct Inner {
    origins: Option<HashSet<Uri>>,
    methods: HashSet<Method>,
    methods_value: HeaderValue,
    headers: Option<HashSet<HeaderName>>,
    headers_value: Option<HeaderValue>,
    max_age: Option<Duration>,
    allow_credentials: bool,
}

fn parse_origin(h: &HeaderValue) -> Result<Uri, CorsError> {
    let h_str = h.to_str().map_err(|_| CorsErrorKind::InvalidOrigin)?;
    let origin_uri: Uri = h_str.parse().map_err(|_| CorsErrorKind::InvalidOrigin)?;

    if origin_uri.scheme_part().is_none() {
        return Err(CorsErrorKind::InvalidOrigin.into());
    }

    if origin_uri.host().is_none() {
        return Err(CorsErrorKind::InvalidOrigin.into());
    }

    Ok(origin_uri)
}

impl Inner {
    fn validate_origin_header(&self, request: &Request<()>) -> Result<AllowedOrigin, CorsError> {
        let origin = request
            .headers()
            .get(header::ORIGIN)
            .ok_or_else(|| CorsErrorKind::MissingOrigin)?;
        let parsed_origin = parse_origin(origin)?;

        if let Some(ref origins) = self.origins {
            if !origins.contains(&parsed_origin) {
                return Err(CorsErrorKind::DisallowedOrigin.into());
            }
            return Ok(AllowedOrigin::Some(origin.clone()));
        }

        if self.allow_credentials {
            Ok(AllowedOrigin::Some(origin.clone()))
        } else {
            Ok(AllowedOrigin::Any)
        }
    }

    fn validate_request_method(
        &self,
        request: &Request<()>,
    ) -> Result<Option<HeaderValue>, CorsError> {
        match request.headers().get(header::ACCESS_CONTROL_REQUEST_METHOD) {
            Some(h) => {
                let method: Method = h
                    .to_str()
                    .map_err(|_| CorsErrorKind::InvalidRequestMethod)?
                    .parse()
                    .map_err(|_| CorsErrorKind::InvalidRequestMethod)?;
                if self.methods.contains(&method) {
                    Ok(Some(self.methods_value.clone()))
                } else {
                    Err(CorsErrorKind::DisallowedRequestMethod.into())
                }
            }
            None => Ok(None),
        }
    }

    fn validate_request_headers(
        &self,
        request: &Request<()>,
    ) -> Result<Option<HeaderValue>, CorsError> {
        match request
            .headers()
            .get(header::ACCESS_CONTROL_REQUEST_HEADERS)
        {
            Some(hdrs) => match self.headers {
                Some(ref headers) => {
                    let mut request_headers = HashSet::new();
                    let hdrs_str = hdrs
                        .to_str()
                        .map_err(|_| CorsErrorKind::InvalidRequestHeaders)?;
                    for hdr in hdrs_str.split(',').map(|s| s.trim()) {
                        let hdr: HeaderName = hdr
                            .parse()
                            .map_err(|_| CorsErrorKind::InvalidRequestHeaders)?;
                        request_headers.insert(hdr);
                    }

                    if !headers.is_superset(&request_headers) {
                        return Err(CorsErrorKind::DisallowedRequestHeaders.into());
                    }

                    Ok(self.headers_value.clone())
                }
                None => Ok(Some(hdrs.clone())),
            },
            None => Ok(None),
        }
    }

    fn handle_preflight_request(
        &self,
        request: &Request<()>,
    ) -> Result<Either<Response<()>, AllowedOrigin>, CorsError> {
        let origin = self.validate_origin_header(request)?;
        match *request.method() {
            Method::OPTIONS => match self.validate_request_method(request)? {
                Some(allow_methods) => {
                    let allow_headers = self.validate_request_headers(request)?;

                    let mut response = Response::new(());
                    response
                        .headers_mut()
                        .insert(header::ACCESS_CONTROL_ALLOW_ORIGIN, origin.into());
                    response
                        .headers_mut()
                        .insert(header::ACCESS_CONTROL_ALLOW_METHODS, allow_methods);

                    if let Some(allow_headers) = allow_headers {
                        response
                            .headers_mut()
                            .insert(header::ACCESS_CONTROL_ALLOW_HEADERS, allow_headers);
                    }

                    if let Some(max_age) = self.max_age {
                        response
                            .headers_mut()
                            .insert(header::ACCESS_CONTROL_MAX_AGE, max_age.as_secs().into());
                    }

                    Ok(Either::Left(response))
                }
                None => Ok(Either::Right(origin)),
            },
            ref method if self.methods.contains(method) => Ok(Either::Right(origin)),
            _ => Err(CorsErrorKind::DisallowedRequestMethod.into()),
        }
    }
}

impl<E> IsEndpoint for CorsEndpoint<E> where E: IsEndpoint {}

impl<E, Bd> Endpoint<Bd> for CorsEndpoint<E>
where
    E: Endpoint<Bd>,
{
    type Output = (CorsResponse<E::Output>,);
    type Action = CorsAction<Bd, E>;

    fn action(&self) -> Self::Action {
        CorsAction {
            action: self.endpoint.action(),
            inner: self.inner.clone(),
            allowed_origin: None,
        }
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct CorsAction<Bd, E: Endpoint<Bd>> {
    action: E::Action,
    inner: Arc<Inner>,
    allowed_origin: Option<AllowedOrigin>,
}

impl<E, Bd> EndpointAction<Bd> for CorsAction<Bd, E>
where
    E: Endpoint<Bd>,
{
    type Output = (CorsResponse<E::Output>,);

    fn preflight(
        &mut self,
        cx: &mut PreflightContext<'_>,
    ) -> Result<Preflight<Self::Output>, Error> {
        match self.inner.handle_preflight_request(cx.request())? {
            Either::Left(response) => Ok(Preflight::Completed((CorsResponse(
                CorsResponseKind::Preflight(response),
            ),))),
            Either::Right(allowed_origin) => {
                self.allowed_origin = Some(allowed_origin);
                Ok(Preflight::Incomplete)
            }
        }
    }

    fn poll_action(&mut self, cx: &mut ActionContext<'_, Bd>) -> Poll<Self::Output, Error> {
        if let Some(allowed_origin) = self.allowed_origin.take() {
            cx.response_headers()
                .append(header::ACCESS_CONTROL_ALLOW_ORIGIN, allowed_origin.into());
            if self.inner.allow_credentials {
                cx.response_headers().append(
                    header::ACCESS_CONTROL_ALLOW_CREDENTIALS,
                    HeaderValue::from_static("true"),
                );
            }
        }
        self.action
            .poll_action(cx)
            .map(|x| x.map(|output| (CorsResponse(CorsResponseKind::Normal(output)),)))
    }
}

#[allow(missing_docs)]
#[derive(Debug)]
pub struct CorsResponse<T>(CorsResponseKind<T>);

#[derive(Debug)]
enum CorsResponseKind<T> {
    Preflight(Response<()>),
    Normal(T),
}

impl<T: IntoResponse> IntoResponse for CorsResponse<T> {
    type Body = izanami_util::buf_stream::Either<Vec<u8>, T::Body>;

    fn into_response(self, request: &Request<()>) -> Response<Self::Body> {
        match self.0 {
            CorsResponseKind::Preflight(response) => {
                response.map(|_| izanami_util::buf_stream::Either::Left(vec![]))
            }
            CorsResponseKind::Normal(normal) => normal
                .into_response(request)
                .map(izanami_util::buf_stream::Either::Right),
        }
    }
}

#[derive(Debug, Clone)]
enum AllowedOrigin {
    Some(HeaderValue),
    Any,
}

impl Into<HeaderValue> for AllowedOrigin {
    fn into(self) -> HeaderValue {
        match self {
            AllowedOrigin::Some(v) => v,
            AllowedOrigin::Any => HeaderValue::from_static("*"),
        }
    }
}

#[allow(missing_docs)]
#[derive(Debug, Fail)]
#[fail(display = "Invalid CORS request: {}", kind)]
pub struct CorsError {
    kind: CorsErrorKind,
}

impl From<CorsErrorKind> for CorsError {
    fn from(kind: CorsErrorKind) -> CorsError {
        CorsError { kind }
    }
}

impl HttpError for CorsError {
    fn status_code(&self) -> StatusCode {
        StatusCode::BAD_REQUEST
    }
}

impl CorsError {
    #[allow(missing_docs)]
    pub fn kind(&self) -> &CorsErrorKind {
        &self.kind
    }
}

#[allow(missing_docs)]
#[derive(Debug, Fail)]
pub enum CorsErrorKind {
    #[fail(display = "the Origin is missing.")]
    MissingOrigin,

    #[fail(display = "the provided Origin is not a valid value.")]
    InvalidOrigin,

    #[fail(display = "the provided Origin is not allowed.")]
    DisallowedOrigin,

    #[fail(display = "the provided Access-Control-Request-Method is not a valid value.")]
    InvalidRequestMethod,

    #[fail(display = "the provided Access-Control-Request-Method is not allowed.")]
    DisallowedRequestMethod,

    #[fail(display = "the provided Access-Control-Request-Headers is not a valid value.")]
    InvalidRequestHeaders,

    #[fail(display = "the provided Access-Control-Request-Headers is not allowed.")]
    DisallowedRequestHeaders,
}
