(function() {var implementors = {};
implementors["finchers"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"finchers/endpoint/ext/struct.NotMatched.html\" title=\"struct finchers::endpoint::ext::NotMatched\">NotMatched</a>",synthetic:false,types:["finchers::endpoint::ext::NotMatched"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"finchers/endpoint/syntax/encoded/struct.DecodeEncodedStrError.html\" title=\"struct finchers::endpoint::syntax::encoded::DecodeEncodedStrError\">DecodeEncodedStrError</a>",synthetic:false,types:["finchers::endpoint::syntax::encoded::DecodeEncodedStrError"]},{text:"impl&lt;E&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"finchers/endpoint/syntax/encoded/struct.ParseEncodedStrError.html\" title=\"struct finchers::endpoint::syntax::encoded::ParseEncodedStrError\">ParseEncodedStrError</a>&lt;E&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;E: Fail + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + 'static,&nbsp;</span>",synthetic:false,types:["finchers::endpoint::syntax::encoded::ParseEncodedStrError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for dyn <a class=\"trait\" href=\"finchers/error/trait.HttpError.html\" title=\"trait finchers::error::HttpError\">HttpError</a>",synthetic:false,types:["finchers::error::HttpError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"finchers/error/struct.Error.html\" title=\"struct finchers::error::Error\">Error</a>",synthetic:false,types:["finchers::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"finchers/util/enum.Never.html\" title=\"enum finchers::util::Never\">Never</a>",synthetic:false,types:["finchers::util::Never"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
